export const ENUM_NAMES = {
  USER_ROLE: 'UserRole',
  AUTH_PROVIDER: 'AuthProvider',
  COUNTRY_CODE: 'CountryCode',
  CURRENCY_CODE: 'CurrencyCode',
  TRANSACTION_TYPE: 'TransactionType',
  RECURRING_FREQUENCY: 'RecurringFrequency',
  RECURRING_TRANSACTION_STATUS: 'RecurringTransactionStatus',
  BUDGET_PERIOD: 'BudgetPeriod',
  BUDGET_STATUS: 'BudgetStatus',
  SORT_ORDER: 'SortOrder',
  AUDIT_LOG_SORT_BY: 'AuditLogSortBy',
  RECURRING_TRANSACTION_SORT_BY: 'RecurringTransactionSortBy',
  TRANSACTION_SORT_BY: 'TransactionSortBy',
  USER_SORT_BY: 'UserSortBy',
  BUDGET_SORT_BY: 'BudgetSortBy',
  DEFAULT_CATEGORY_SORT_BY: 'DefaultCategorySortBy',
  CATEGORY_SORT_BY: 'CategorySortBy',
  EXPORT_FORMAT: 'ExportFormat',
  GRANULARITY: 'Granularity',
} as const;
